/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio1;

/**
 *
 * @author AlejandroMarínBermúd
 */
public class Calculadora extends javax.swing.JFrame {

    String num1;
    String signo;
    String num2;
    
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        BotonC = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Suma = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Dividir = new javax.swing.JButton();
        Multiplica = new javax.swing.JButton();
        BotonComa = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        RaizC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(4, 10, 10, 0));

        Boton7.setText("7");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton7);

        Boton8.setText("8");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton8);

        Boton9.setText("9");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton9);

        BotonC.setText("C");
        BotonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCActionPerformed(evt);
            }
        });
        jPanel1.add(BotonC);

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        jPanel1.add(Borrar);

        Boton4.setText("4");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton4);

        Boton5.setText("5");
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton5);

        Boton6.setText("6");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton6);

        Suma.setText("+");
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });
        jPanel1.add(Suma);

        Resta.setText("-");
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });
        jPanel1.add(Resta);

        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1);

        Boton2.setText("2");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton2);

        Boton3.setText("3");
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton3);

        Dividir.setText("/");
        Dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DividirActionPerformed(evt);
            }
        });
        jPanel1.add(Dividir);

        Multiplica.setText("X");
        Multiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicaActionPerformed(evt);
            }
        });
        jPanel1.add(Multiplica);

        BotonComa.setText(".");
        BotonComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComaActionPerformed(evt);
            }
        });
        jPanel1.add(BotonComa);

        Boton0.setText("0");
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton0);

        Igual.setText("=");
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });
        jPanel1.add(Igual);

        RaizC.setText("Raiz");
        RaizC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaizCActionPerformed(evt);
            }
        });
        jPanel1.add(RaizC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addComponent(Pantalla))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+"7");
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+"9");
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+"8");
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+"4");
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+"5");
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+"6");
    }//GEN-LAST:event_Boton6ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
    // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+ "1");
    }//GEN-LAST:event_boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        Pantalla.setText(Pantalla.getText()+"2");       
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+"3");
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        // TODO add your handling code here:
        Pantalla.setText(Pantalla.getText()+"0");
    }//GEN-LAST:event_Boton0ActionPerformed

    private void BotonComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComaActionPerformed
        // TODO add your handling code here:
       String cadena;
       cadena = Pantalla.getText();
       
       if(cadena.length()<=0){
           Pantalla.setText("0.");
       }
       else{
           if(!existepunto(Pantalla.getText())){
               Pantalla.setText(Pantalla.getText() + ".");
           }
       }
    }//GEN-LAST:event_BotonComaActionPerformed

    public static boolean existepunto(String cadena){
     
        boolean resultado;
        resultado = false;
        
        for(int i = 0; i< cadena.length();i++){
            if(cadena.substring(i, i+1).equals(".")){
                resultado = true;
                break;
            }
        }
        return resultado;
    }
    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        // TODO add your handling code here:
           if(!Pantalla.getText().equals("")){
            num1=Pantalla.getText();
            signo="+";
            Pantalla.setText("");
        }
    }//GEN-LAST:event_SumaActionPerformed

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
        // TODO add your handling code here:
        if(!Pantalla.getText().equals("")){
            num1=Pantalla.getText();
            signo="-";
            Pantalla.setText("");
        }
            
    }//GEN-LAST:event_RestaActionPerformed

    private void MultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicaActionPerformed
        // TODO add your handling code here:
          if(!Pantalla.getText().equals("")){
            num1=Pantalla.getText();
            signo="*";
            Pantalla.setText("");
        }
    }//GEN-LAST:event_MultiplicaActionPerformed

    private void DividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DividirActionPerformed
   if(!Pantalla.getText().equals("")){
            num1=Pantalla.getText();
            signo="/";
            Pantalla.setText("");
        }        // TODO add your handling code here:
     
    }//GEN-LAST:event_DividirActionPerformed

    private void BotonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCActionPerformed
        // TODO add your handling code here:
       Pantalla.setText("");
        
    }//GEN-LAST:event_BotonCActionPerformed

    private void RaizCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaizCActionPerformed
        // TODO add your handling code here:
        String cadena;
        Double num;
        cadena = Pantalla.getText();
        
       if(cadena.length()>0){
           num = Math.sqrt(Double.parseDouble(cadena));
           Pantalla.setText(num.toString());
       } 
    }//GEN-LAST:event_RaizCActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
        String resultado;
        num2 = Pantalla.getText();
        
        if(!num2.equals("")){
            resultado = calculadora(num1,num2,signo);
            Pantalla.setText(resultado);
        }
    }//GEN-LAST:event_IgualActionPerformed
    public static String calculadora(String num1, String num2, String signo){
        
        Double resultado = 0.0;
        String respuesta;
        
        if(signo.equals("-")){
            resultado = Double.parseDouble(num1) - Double.parseDouble(num2);
        }
        else if(signo.equals("+")){
             resultado = Double.parseDouble(num1) + Double.parseDouble(num2);
        }
        else if(signo.equals("/")){
             resultado = Double.parseDouble(num1) / Double.parseDouble(num2);
        }
        else if(signo.equals("*")){
             resultado = Double.parseDouble(num1) * Double.parseDouble(num2);
        }
              
        respuesta = resultado.toString();
        return respuesta;
    }
    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
         String cadena;
        cadena = Pantalla.getText();
        
        if(cadena.length() > 0 ){
          cadena =  cadena.substring(0, cadena.length()-1);
          Pantalla.setText(cadena);
        }
    }//GEN-LAST:event_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonComa;
    private javax.swing.JButton Dividir;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Multiplica;
    private javax.swing.JTextField Pantalla;
    private javax.swing.JButton RaizC;
    private javax.swing.JButton Resta;
    private javax.swing.JButton Suma;
    private javax.swing.JButton boton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
